language: php

php:
- 7.2

env:
  global:
  - DEFAULT=0

matrix:
  include:
  - php: 7.2
    env: PHPCS=1 DEFAULT=0

  fast_finish: true

before_script:
- COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

script:
- sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/codecept run; fi"
- sh -c "if [ '$PHPCS' = '1' ]; then composer cs-check ; fi"

notifications:
  email: false
